### ISSUE TITLE
Add VersionBot integration

### ISSUE THREAD

**Issue by lurch** [resin-io-modules/mountutils#47]

**Comment by jhermsmeier** [comment]
Yup

**Comment by jhermsmeier** [comment]
Closing as Versionbot integration has been added

**Comment by lurch** [comment]
...although slightly incorrectly ;-)

**Comment by jhermsmeier** [comment]
What is incorrect? Anything missing / wrong with it?

**Comment by jhermsmeier** [comment]
Oh, I see – the changelog got messed up.
